name: Test App

on:
  workflow_dispatch:
    inputs:
      ac-user:
        description: "AC service account user"
        required: true
        default: ""
      ac-pwd:
        description: "AC service account password"
        required: true
        default: ""
      app-name:
       description: "Name of the app"
       required: true
       default: "Test App"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "ReplaceToken: APP_NAME"
        uses: ./.github/actions/replace-token
        with:
          filename: "vars.yml"
          name: "APP_NAME"
          value: ${{ github.event.inputs.app-name }}

      - name: Deploy to AC
        uses: ./.github/actions/deploy-to-ac
        env:
          CF_USERNAME: ${{ github.event.inputs.ac-user }}
          CF_PASSWORD: ${{ github.event.inputs.ac-pwd }}
        with:
          var-file: "vars.yml"
          space: "GradFreshstart"
          manifest: "frontend/manifest.yml"
          path: "./frontend"
